### ISSUE TITLE
在mac上显示有问题

### ISSUE THREAD

**Issue by Z-fly** [WankkoRee/BurpLoaderKeygenCnF#1]
![image](https://user-images.githubusercontent.com/10470892/132611291-e43f5cbc-2d05-41d4-a4f7-af9b7628fd5f.png)

**Comment by Z-fly** [comment]
汉化那里

**Comment by WankkoRee** [comment]
ok了解 应该是字体大小和字宽的问题

**Comment by Z-fly** [comment]
补充下翻译：
![image](https://user-images.githubusercontent.com/10470892/132612489-f883e730-f4d7-47d5-a2ad-1f2de55a82be.png)
日志(Logger)

![image](https://user-images.githubusercontent.com/10470892/132612552-8a255cda-c5b3-4b0a-8c76-0d84198c9120.png)
学习(Learn)

**Comment by WankkoRee** [comment]
已尝试修复显示问题，汉化建议已收录，你可以尝试：[v1.0.2](https://github.com/WankkoRee/BurpLoaderKeygenCnF/releases/tag/v1.0.2)

**Comment by Z-fly** [comment]
![image](https://user-images.githubusercontent.com/10470892/132628105-b79c7cf6-675e-4039-bb48-475cbade0cea.png)
现在打开是这样的效果

**Comment by WankkoRee** [comment]
改了下宽度的实现方式，现在应该可以了：[v1.0.3](https://github.com/WankkoRee/BurpLoaderKeygenCnF/releases/tag/v1.0.3)
