### ISSUE TITLE
该更新了大佬！

### ISSUE THREAD

**Issue by yuhanghai** [WankkoRee/BurpLoaderKeygenCnF#10]
burpsuite_pro_v2022.3.4.jar 无法使用

**Comment by WankkoRee** [comment]
我看起来似乎没有遇到问题，请问你出现了什么问题呢？

![image](https://user-images.githubusercontent.com/21287731/163716761-bc505401-5aa9-4b92-8eb9-7db93be49eb0.png)

**Comment by ppofp** [comment]
点击运行闪退



---- 回复的原邮件 ----
| 发件人 | Wankko ***@***.***> |
| 日期 | 2022年04月17日 21:38 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [WankkoRee/BurpLoaderKeygenCnF] 该更新了大佬！ (Issue #10) |

我看起来似乎没有遇到问题，请问你出现了什么问题呢？

**Comment by WankkoRee** [comment]
复制命令行并手动运行，将报错截图或复制给我。
