### ISSUE TITLE
【BUG】Windows下无法使用

### ISSUE THREAD

**Issue by Z-fly** [WankkoRee/BurpLoaderKeygenCnF#16]
https://github.com/h3110w0r1d-y/BurpLoaderKeygen 这个是可以的

**Comment by WankkoRee** [comment]
具体情况呢？

命令行启动时是否有报错？

**Comment by Z-fly** [comment]
![image](https://user-images.githubusercontent.com/10470892/206886722-df956b0d-fb4c-4098-9b77-b1136abaecc5.png)
一直是弹这个

**Comment by WankkoRee** [comment]
有尝试过`v1.1.2`吗？

**Comment by Z-fly** [comment]
"java" "--add-opens=java.desktop/javax.swing=ALL-UNNAMED" "--add-opens=java.base/java.lang=ALL-UNNAMED" "--add-opens=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED" "--add-opens=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED" "--add-opens=java.base/jdk.internal.org.objectweb.asm.Opcodes=ALL-UNNAMED" "-javaagent:BurpLoaderKeygenCnF.jar=cn" "-noverify" "-jar" "burpsuite_pro_v2022.12.2.jar"

**Comment by Z-fly** [comment]
解决了 正确的启动命令

**Comment by WankkoRee** [comment]
这似乎是java版本差异造成的。

**Comment by Z-fly** [comment]
那最好也要适配下

**Comment by Z-fly** [comment]
那最好也要适配下

**Comment by Z-fly** [comment]
@WankkoRee 经过测试，最新版的Burp已经不支持JDK11了。

**Comment by WankkoRee** [comment]
已在 [v1.1.3](https://github.com/WankkoRee/BurpLoaderKeygenCnF/releases/tag/v1.1.3) 中加上相关参数，感谢。

**Comment by WankkoRee** [comment]
希望反馈新版本是否解决了这一问题。

**Comment by Z-fly** [comment]
解决了
