### ISSUE TITLE
【Bug】v1.1.2无法激活2022.11.x及2022.12.x

### ISSUE THREAD

**Issue by Indekkusu545** [WankkoRee/BurpLoaderKeygenCnF#17]
1.1.2激活2022.11.x和2022.12.x，提示密钥无效。
Java版本：JDK 17.0.5

**Comment by Indekkusu545** [comment]
目前使用的是v1.1.1激活了2022.9.6，在已经激活的2022.9.6里用v1.1.2的密钥可以更新许可证，但是2022.11.x就无法激活。

**Comment by Z-fly** [comment]
"java" "--add-opens=java.desktop/javax.swing=ALL-UNNAMED" "--add-opens=java.base/java.lang=ALL-UNNAMED" "--add-opens=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED" "--add-opens=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED" "--add-opens=java.base/jdk.internal.org.objectweb.asm.Opcodes=ALL-UNNAMED" "-javaagent:BurpLoaderKeygenCnF.jar=cn" "-noverify" "-jar" "burpsuite_pro_.jar"

**Comment by Z-fly** [comment]
#16

**Comment by WankkoRee** [comment]
已在 [v1.1.3](https://github.com/WankkoRee/BurpLoaderKeygenCnF/releases/tag/v1.1.3) 中加上相关参数，感谢。

**Comment by Indekkusu545** [comment]
谢谢
