### ISSUE TITLE
2021.8.3的许可证密钥格式有了变动

### ISSUE THREAD

**Issue by Z-fly** [WankkoRee/BurpLoaderKeygenCnF#2]

**Comment by WankkoRee** [comment]
![image](https://user-images.githubusercontent.com/21287731/133719604-ccb3c5af-ad9e-4af7-91bb-4570c6256f95.png)

我这测试一切正常。

**Comment by Z-fly** [comment]
https://user-images.githubusercontent.com/10470892/133720685-2d254a29-8359-491e-bdd2-0b96b8151392.mov

难道是我用jdk17的缘故？

**Comment by WankkoRee** [comment]
ok i will try it again

**Comment by WankkoRee** [comment]
确实是jdk17的问题，请尝试降级jdk版本，现在官方推荐的版本是9~14.

**Comment by Z-fly** [comment]
这个是修不了吧

**Comment by Z-fly** [comment]
Burp本体用jdk17有兼容性问题

**Comment by WankkoRee** [comment]
这是burp官方的问题，理论上即使是正版激活码在jdk17的环境下也会存在这个问题。

不建议从本项目进行破坏性修复，因为需要代理burp本身那些与jdk17不适配的函数。而且即使修好了激活码识别问题，也很可能存在其他未被发现的因为不适配jdk17导致的bug。

最好就是降低jdk版本后等官方适配。
