### ISSUE TITLE
支持设置绝对路径

### ISSUE THREAD

**Issue by Z-fly** [WankkoRee/BurpLoaderKeygenCnF#4]
当前在win上如果没设置环境变量，就无法自动执行了

**Comment by WankkoRee** [comment]
是指jre的绝对路径还是burp的绝对路径？

**Comment by Z-fly** [comment]
两个都指定绝对路径

**Comment by WankkoRee** [comment]
ok！我会抽空去实现的。

**Comment by Z-fly** [comment]
如果一个设置绝对路径，另一个相对路径的话，以前一个为基准
这样大家的电脑基本都可以适配了

**Comment by Baikeryoyo** [comment]
如果电脑安装了jre，还是手动增加环境变量的好，如果你使用的便携式jre，建议burp和jre放在同一个目录下，以达到不同版本的适配
我为需要不同java的版本的程序，都配置了不同版本的便携式jre

**Comment by 4rat** [comment]
其实我觉得可以自定义启动命令就可以了，默认用作者的，如果有更改的话直接把改过的写入到配置文件，这样的话就可以通过自定义启动命令来实现不同的jdk来加载了。

**Comment by WankkoRee** [comment]
已实现。
