### ISSUE TITLE
建议新增图标功能

### ISSUE THREAD

**Issue by 4rat** [WankkoRee/BurpLoaderKeygenCnF#5]
首先感谢作者，这是一个很好的项目
建议在启动参数处增加添加burp原版图标功能

**Comment by 4rat** [comment]
补充：授权描述功能好像无效

**Comment by WankkoRee** [comment]
1. 本项目未对burp图标进行替换，除文字外的所有显示效果均为burp原版效果。
2. 授权描述的文本会被写入到许可证中，并不会每次启动时都进行注入，所以你burp中显示的授权描述为你激活时所用许可证的内置文本，如需修改请重置许可证。

**Comment by 4rat** [comment]
可能我表述有不对的地方
1.我指的增加图标是指在启动命令处增加java -noverify -Xdock:icon=BurpSuite.icns，这样的话 java程序打开就会加载burp图标，但是修改后不会默认保存。

**Comment by WankkoRee** [comment]
嗨，`BurpSuite.icns`这个文件似乎并不存在于 burp 官方 jar 包中，后续本项目应该会拆分加载命令为 必要参数字段 和 自定义参数字段，后者可保存使用者自定义的相关参数，敬请期待。
